### PR TITLE
DefaultTracer#writeTo now tolerates NoopTracer

### LINKED ISSUE #522: Opentracing-FlowID breaks when used with a NoopTracer
## Description

When running with a NoopTracer, DefaultFlow.writeTo(...) fails with an IllegalStateException (because currentId throws such an exception).

## Expected Behavior

If there is no flow-ID information available, `Flow.writeTo(...)` should either just not write anything, or should write a default value (but I don't think that's useful).

## Actual Behavior

`DefaultFlow.writeTo(BiConsumer<String, String>)` is throwing an IllegalStateException (actually in DefaultFlow.currentId()).

## Possible Fix

I'm not sure which of those options is best:

* make `writeTo(...)` not using `currentId()`, but use most of its implementation directly, something like this:
   ```java
       @Override
       public void writeTo(final BiConsumer<String, String> writer) {
          extractor.extract(activeSpan())
                   .map(FlowId::getValue)
                   .ifPresent(value -> writer.accept(Header.FLOW_ID, value));
       }
   ```
   _(Though I wonder why the key of the FlowId object is ignored?)_
* make `currentId()` not throwing (when no flow-ID is available)
* catch the exception from currentId() in writeTo().

## Steps to Reproduce

1. create a NoopTracer (from io.opentracing:opentracing-noop).
2. create a DefaultFlow with this NoopTracer.
3. get an arbitrary BiConsumer (e.g. `consumer = (a,b) -> log.debug("{}: {}", a, b)`).
4. call `flow.writeTo(consumer)`.

## Context

When using Zalando's internal telemetry-setup library, when no Lightstep environment variables are available, a NoopTracer is injected, whose NoopSpan will not keep any baggage items.

When combined with the setup from opentracing-flowid-starter, I get this error when a request with a `x-flow-id` header is processed by `FlowFilter` (from opentracing-flowid-servlet). When not using this header, the exception is not thrown, as this `writeTo` is only called when the header is present in the request. (I think this is a bit backwards – I would like to get the flow-ID in the response even if it's missing in the request (e.g. for requests from the command line). If it's in the request, it's less needed in the response, as the caller already knows it.)

When doing outgoing requests (e.g. via riptide), I get this error from `FlowHttpRequestInterceptor` (from opentracing-flowid-httpclient), which is trying to put the flow-ID into the HTTP header of the created request.

This makes it impossible to run our program locally without actually setting up the connections to Lightstep.

## Your Environment

* Version used: 4.0.0
* Link to your project: [Zalando-internal link](https://github.bus.zalan.do/lightning/purchase-orders-ean-label-generator)

### PR DESCRIPTION
**Pull request by ePaul**
## Description

When used with a NoopTracer (or generally any Span which doesn't allow extracting any useful identifier), DefaultFlow.writeTo now will just not do anything, instead of throwing an IllegalStateException.

## Motivation and Context

It allows running an application when no proper tracing implementation is available, e.g. when running it locally.
This should fix #522.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

If any user depended on an exception being thrown by `Flow.writeTo(...)` in this case, this would break.
But as there is no documentation for writeTo, it's unclear whether this is part of the contract or not.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

I didn't find any documentation of `writeTo`, so I don't think there is any which needs to be updated.

### CODE REVIEW

**Comment by ePaul** [comment]
In #522 I've mentioned three possible ways of solving this (and there might be others).
This implements the one I find most reasonable.

Feel free to reject this if you think it should be done differently.

File: opentracing-flowid/opentracing-flowid/src/test/java/org/zalando/opentracing/flowid/DefaultFlowNoopTracerTest.java [hunk 1]
```diff
@@ -1,15 +1,39 @@
...
     }
+
+    @Test
+    void writeToShouldNotThrow() {
+        final Span span = tracer.buildSpan("test").start();
+
+        try (final Scope ignored = tracer.activateSpan(span)) {
+            final Map<String, String> target = new HashMap<>();
+
+            unit.writeTo(target::put);
```
Comment (ePaul) [inline opentracing-flowid/opentracing-flowid/src/test/java/org/zalando/opentracing/flowid/DefaultFlowNoopTracerTest.java:34]: This line was previously failing with the IllegalStateException.

File: opentracing-flowid/opentracing-flowid/src/test/java/org/zalando/opentracing/flowid/DefaultFlowNoopTracerTest.java [hunk 2]
```diff
@@ -12,4 +17,11 @@
     void shouldThrowNoActiveSpanFoundException() {
         assertThrows(IllegalStateException.class, unit::currentId);
     }
+
+    @Test
+    void writeToShouldNotThrow() {
+        final Map<String, String> target = new HashMap<>();
+        unit.writeTo(target::put);
+        assertEquals(emptyMap(), target);
+    }
```
Comment (ePaul) [inline opentracing-flowid/opentracing-flowid/src/test/java/org/zalando/opentracing/flowid/DefaultFlowNoopTracerTest.java:26]: This test was (before the fix) failing with an IllegalStateException in the `unit.writeTo` line.
Now it just does nothing (as proven by the assert).

File: opentracing-flowid/opentracing-flowid/src/test/java/org/zalando/opentracing/flowid/DefaultFlowNoopTracerTest.java [hunk 3]
```diff
@@ -12,4 +17,11 @@
     void shouldThrowNoActiveSpanFoundException() {
```
Comment (zeitlinger) [inline opentracing-flowid/opentracing-flowid/src/test/java/org/zalando/opentracing/flowid/DefaultFlowNoopTracerTest.java:17]: Not throwing exceptions is the right direction here - can we also make this test now throw?

File: opentracing-flowid/opentracing-flowid/src/main/java/org/zalando/opentracing/flowid/DefaultFlow.java [hunk 4]
```diff
@@ -59,7 +59,10 @@ public String currentId() {
 
     @Override
     public void writeTo(final BiConsumer<String, String> writer) {
-        writer.accept(Header.FLOW_ID, currentId());
+        extractor.extract(activeSpan())
```
Comment (zeitlinger) [inline opentracing-flowid/opentracing-flowid/src/main/java/org/zalando/opentracing/flowid/DefaultFlow.java:62]: would it make sense to change the other `writeTo` method in the same way?

**Comment by zeitlinger** [comment]
> In #522 I've mentioned three possible ways of solving this (and there might be others).
> This implements the one I find most reasonable.
> 
> Feel free to reject this if you think it should be done differently.

Thanks a lot for the help :smile:

File: opentracing-flowid/opentracing-flowid/src/main/java/org/zalando/opentracing/flowid/DefaultFlow.java (hunk 4 above)
Comment (ePaul) [reply opentracing-flowid/opentracing-flowid/src/main/java/org/zalando/opentracing/flowid/DefaultFlow.java:62]: You mean the `write(BiFunction<String, String, T>)` method? That one returns a `T` which is coming from the passed BiFunction.
I guess I could return null when we decide to not call it, but that might be as surprising to callers as directly throwing the IllegalStateException.

File: opentracing-flowid/opentracing-flowid/src/test/java/org/zalando/opentracing/flowid/DefaultFlowNoopTracerTest.java (hunk 3 above)
Comment (ePaul) [reply opentracing-flowid/opentracing-flowid/src/test/java/org/zalando/opentracing/flowid/DefaultFlowNoopTracerTest.java:17]: Not throw?
If you tell me what `currentId()` should return when there is no active span, sure. Just null?

**Comment by zeitlinger** [comment]
:+1:

**Comment by zeitlinger** [comment]
:+1:
